# This workflow will do a clean install of node dependencies, execute the linters and run tests across different versions of node

name: Code Quality tools

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm test
        env:
          CI: true
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run now-build
      - run: now storybook-static/ --prod -t ${{ secrets.ZEIT_TOKEN }}
